<?php
/*
 * @ https://EasyToYou.eu - IonCube v10 Decoder Online
 * @ PHP 5.6
 * @ Decoder version: 1.0.3
 * @ Release: 10.12.2019
 *
 * @ ZendGuard Decoder PHP 5.6
 */

$metaboxes["SelaryOptions"] = array("context" => "normal", "priority" => "high", "taxonomy" => array("selary", "tvshow", "assemblies"), "name" => "اعدادات المواسم ", "nameEN" => "Additional options", "type" => "fields", "fields" => array(array("name" => "الاسم المختصر ", "nameEN" => "Short Name", "type" => "text", "id" => "shortname"), array("name" => "رقم الموسم ", "nameEN" => "Session Number", "type" => "text", "id" => "order"), array("name" => "جديد", "nameEN" => "New", "type" => "checkbox", "id" => "newSeries"), array("name" => "الافضل ", "nameEN" => "best", "type" => "checkbox", "id" => "best"), array("name" => "مشهور ", "nameEN" => "Famous", "type" => "checkbox", "id" => "famous")));
$metaboxes["PostOptions"] = array("context" => "normal", "priority" => "high", "ptype" => array("post"), "name" => "إعدادات العرض", "nameEN" => "Article options", "type" => "fields", "fields" => array(array("name" => "عنوان مختصر", "nameEN" => "brief title", "type" => "text", "id" => "title2"), array("name" => "الملصق", "nameEN" => "Ribbon", "type" => "text", "id" => "ribbon"), array("name" => "ملحوظة عن العمل", "nameEN" => "note1", "type" => "textarea", "id" => "note1"), array("name" => "رقم الحلقة", "nameEN" => "Episode number", "type" => "text", "id" => "number"), array("name" => "مثبت ؟", "nameEN" => "Sticky ?", "type" => "checkbox", "id" => "pin"), array("name" => "مدة العرض", "nameEN" => "Runtime", "type" => "text", "id" => "runtime"), array("name" => "الإعلان", "nameEN" => "Trailer", "type" => "textarea_code", "id" => "trailer"), array("name" => "تاريخ الاصدار", "nameEN" => "Released", "type" => "text", "id" => "released"), array("name" => "برنامج تلفزيوني", "nameEN" => "TvPro", "type" => "checkbox", "id" => "TvPro"), array("name" => "افلام جديدة", "nameEN" => "new movies", "type" => "checkbox", "id" => "new"), array("name" => "افضل الافلام", "nameEN" => "best movies", "type" => "checkbox", "id" => "best"), array("name" => "تقييم IMDB", "nameEN" => "imdbRating", "type" => "text", "id" => "imdbRating"), array("name" => "تصويتات IMDB", "nameEN" => "imdbvotes", "type" => "text", "id" => "imdbVotes")));
$metaboxes["WatchServers"] = array("context" => "normal", "priority" => "high", "ptype" => array("post"), "name" => "سيرفرات المشاهدة", "nameEN" => "Watch servers", "type" => "fields", "fields" => array(array("name" => "سيرفر 1", "type" => "textarea", "id" => "embed_pelicula"), array("name" => "سيرفر 2", "type" => "textarea", "id" => "embed_pelicula2"), array("name" => "سيرفر 3", "type" => "textarea", "id" => "embed_pelicula3"), array("name" => "سيرفر 4", "type" => "textarea", "id" => "embed_pelicula4"), array("name" => "سيرفر 5", "type" => "textarea", "id" => "embed_pelicula5"), array("name" => "سيرفر 6", "type" => "textarea", "id" => "embed_pelicula6"), array("name" => "سيرفر 7", "type" => "textarea", "id" => "embed_pelicula7"), array("name" => "سيرفر 8", "type" => "textarea", "id" => "embed_pelicula8"), array("name" => "سيرفر 9", "type" => "textarea", "id" => "embed_pelicula9"), array("name" => "سيرفر 10", "type" => "textarea", "id" => "embed_pelicula10"), array("name" => "سيرفر 11", "type" => "textarea", "id" => "embed_pelicula11")));
$metaboxes["DownloadServers"] = array("context" => "normal", "priority" => "high", "ptype" => array("post"), "name" => "سيرفرات التحميل", "nameEN" => "Watch servers", "type" => "fields", "fields" => array(array("name" => "روابط التحميل", "nameEN" => "Download Servers", "type" => "group", "id" => "downloads", "fields" => array(array("name" => "الإسم", "nameEN" => "Name", "type" => "text", "id" => "name"), array("name" => "الجودة", "nameEN" => "Quality", "type" => "text", "id" => "quality"), array("name" => "الدقة", "nameEN" => "Resolution", "type" => "text", "id" => "resolution"), array("name" => "الحجم", "nameEN" => "Size", "type" => "text", "id" => "size"), array("name" => "الرابط", "nameEN" => "URL", "type" => "text", "id" => "url")))));
$metaboxes["TaxonomiesOptions"] = array("context" => "normal", "priority" => "high", "taxonomy" => array("actor", "director", "writers"), "name" => "خصائص إضافية", "nameEN" => "Additional options", "type" => "fields", "fields" => array(array("name" => "الصورة", "nameEN" => "Image", "type" => "file", "id" => "image")));
$options = array();
foreach (get_categories(array("taxonomy" => "category", "hide_empty" => 0)) as $cat) {
    $options[$cat->term_id] = $cat->name;
}
$metaboxes["sectionSetting"] = array("context" => "normal", "priority" => "high", "ptype" => array("sections"), "name" => "اعدادات عامة", "nameEN" => "general setting", "type" => "fields", "fields" => array(array("name" => "وصف الشريحة", "nameEN" => "slice description", "type" => "text", "id" => "desc"), array("name" => "تثبيت الشريحة ", "nameEN" => "Pin Section", "type" => "checkbox", "id" => "pinSec"), array("name" => "عدد المواضيع", "nameEN" => "Posts per Page", "type" => "text", "id" => "perpage"), array("name" => "ترتيب الشريحة", "nameEN" => "slice order", "type" => "text", "id" => "order"), array("name" => "ترتيب حسب", "nameEN" => "filter by ", "type" => "radio", "id" => "filteringby", "options" => array("recent" => "الاحدث", "imdb" => " تقييم  imdb", "views" => "المشاهادات", "ratings" => "حسب التقييم", "pin" => "المثبت")), array("name" => "التصنيف", "nameEN" => "category", "type" => "taxonomy_select", "id" => "category", "taxonomy" => "category"), array("name" => "المسلسلات", "nameEN" => "series", "type" => "taxonomy_select", "id" => "ser", "taxonomy" => "selary"), array("name" => "سلاسل الافلام", "nameEN" => "movseries", "type" => "taxonomy_select", "id" => "movseries", "taxonomy" => "assemblies"), array("name" => "النوع", "nameEN" => "genre", "type" => "taxonomy_select", "id" => "genre", "taxonomy" => "genre"), array("name" => "سنة الاصدار", "nameEN" => "year", "type" => "taxonomy_select", "id" => "year", "taxonomy" => "release-year"), array("name" => "الجودة", "nameEN" => "quality", "type" => "taxonomy_select", "id" => "quality", "taxonomy" => "Quality"), array("name" => "اللغة", "nameEN" => "lang", "type" => "taxonomy_select", "id" => "language", "taxonomy" => "language"), array("name" => "ايقونة الاسلايدر", "nameEN" => "section icon", "type" => "file", "id" => "SecIcon")));
$metaboxes["linkSettings"] = array("context" => "normal", "priority" => "high", "ptype" => array("customlink"), "name" => "اعدادات عامة", "nameEN" => "general setting", "type" => "fields", "fields" => array(array("name" => "وصف الشريحة", "nameEN" => "slice description", "type" => "text", "id" => "desc"), array("name" => "العنوان", "nameEN" => "title", "id" => "name_seo", "type" => "text"), array("name" => "الوصف", "nameEN" => "title", "id" => "desc_seo", "type" => "textarea"), array("name" => "كلمات مفتاحية", "nameEN" => "keywords", "id" => "tags_seo", "type" => "text"), array("name" => "صورة الشير", "nameEN" => "image social", "id" => "img_social", "type" => "file"), array("name" => "التصنيف", "nameEN" => "category", "id" => "tag_category", "type" => "select", "options" => $options), array("name" => "الانواع", "nameEN" => "genre", "id" => "genre_category", "type" => "taxonomy_select", "taxonomy" => "genre"), array("name" => "الجودات", "nameEN" => "quality", "id" => "quality_category", "type" => "taxonomy_select", "taxonomy" => "Quality"), array("name" => "الممثل", "nameEN" => "actor", "id" => "actor_category", "type" => "taxonomy_select", "taxonomy" => "actor"), array("name" => "الكاتب", "nameEN" => "writer", "id" => "escritor_category", "type" => "taxonomy_select", "taxonomy" => "escritor"), array("name" => "المخرج", "nameEN" => "director", "id" => "director_category", "type" => "taxonomy_select", "taxonomy" => "director"), array("name" => "السنة", "nameEN" => "years", "id" => "year_category", "type" => "taxonomy_select", "taxonomy" => "release-year")));
$metaboxes["NewsMeta"] = array("context" => "normal", "priority" => "high", "ptype" => array("news"), "name" => "اعدادات  عامة ", "nameEN" => "Post Option", "type" => "fields", "fields" => array(array("name" => "مثبت", "nameEN" => "Pin Post", "type" => "checkbox", "id" => "pinNews")));
$metaboxes["IMDbOptions"] = array("context" => "normal", "priority" => "high", "callback" => get_template_directory() . "/Setup/IMDb/metabox.php", "taxonomy" => array("actor", "director", "writers"), "ptype" => array("post"), "name" => "إعدادات  IMDb", "nameEN" => "IMDb options");
$metaboxes["SeoOption"] = array("context" => "normal", "priority" => "high", "ptype" => array("post"), "name" => "إعدادات الارشفة ", "nameEN" => "Seo options", "type" => "fields", "fields" => array(array("name" => "اسم الارشفة ", "nameEN" => "Seo Name", "type" => "text", "id" => "metatitle"), array("name" => "وصف الارشفة", "nameEN" => "Seo description", "type" => "textarea", "id" => "metadescription"), array("name" => "صورة الشير ", "nameEN" => "Share Image", "type" => "file", "id" => "ogimage")));

?>